version: "3.8"

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: inventory-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=inventory_management
    networks:
      - inventory-network

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: inventory-backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/inventory_management
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    networks:
      - inventory-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: inventory-frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    # environment:
    #   - NEXT_PUBLIC_API_URL=http://backend:5000/api
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - inventory-network

volumes:
  mongodb_data:

networks:
  inventory-network:
    driver: bridge
