name: Backend CI Pipeline

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: |
          cd backend
          MONGOMS_DISABLE_POSTINSTALL=true npm ci

      - name: Run Linter
        run: |
          cd backend
          npm run lint

      - name: Run Test
        run: |
          cd backend
          NODE_ENV=test npx jest --config=jest.config.js
          MONGOMS_DISABLE_POSTINSTALL=true npm test
